In [111]:
import pandas as pd

In [112]:
S = pd.Series([10,20,30,40],index=['a','b','c','d'])

In [113]:
df = pd.DataFrame({
    "name":["adi","jyaew","suresh","lakappa"],
    "dept":["it","sales","market","employee"],
    "salary":[1000,2000,3000,4000],
})

In [114]:
df

      name      dept  salary
0      adi        it    1000
1    jyaew     sales    2000
2   suresh    market    3000
3  lakappa  employee    4000

In [115]:
df.groupby("dept")["salary"].agg(["mean","sum","count"]).reset_index()

       dept    mean   sum  count
0  employee  4000.0  4000      1
1        it  1000.0  1000      1
2    market  3000.0  3000      1
3     sales  2000.0  2000      1

In [118]:
dates=pd.date_range("2026-01-01",periods=10,freq="D")
ts=pd.Series([100,102,103,104,105,110,112,115,113,120],index=dates)

In [120]:
ts.resample("3D").mean()
ts.rolling(window=3).mean()

2026-01-01           NaN
2026-01-02           NaN
2026-01-03    101.666667
2026-01-04    103.000000
2026-01-05    104.000000
2026-01-06    106.333333
2026-01-07    109.000000
2026-01-08    112.333333
2026-01-09    113.333333
2026-01-10    116.000000
Freq: D, dtype: float64